In [1]:
import torch

In [2]:
dtype = torch.FloatTensor
# dtype = torch.cuda.FloatTensor # Uncomment this to run on GPU

In [3]:
true_m, true_b = 0.5, -0.25
N = 50
x = torch.linspace(-5, 5, N).type(dtype)
y = true_m * x + true_b

#Introduce some noise with both measurement uncertainties
#   and non-trivial correlated errors.
yerr = 0.1 + 0.4 * torch.rand(N).type(dtype)
yerr_hom = 0.4*torch.ones(N).type(dtype)
hom_cov = torch.diag(yerr_hom ** 2).type(dtype)
iid_cov = torch.diag(yerr ** 2).type(dtype)
true_cov = 0.5 * torch.exp(-0.5 * (x[:, None]-x[None, :])**2 / 1.3**2) + torch.diag(yerr ** 2)

Multivariate normal is now in the master branch of pytorch as of v 0.4!

In [4]:
y_draw = torch.distributions.multivariate_normal.MultivariateNormal(y, covariance_matrix=true_cov).sample()

In [5]:
y_draw.dtype

torch.float32

In [6]:
A = torch.ones((N,2))
A[:, 0] = x

AT= A.t()
C = true_cov

In [7]:
factor = torch.potrf(C)

In [8]:
S_inv = torch.mm(AT, torch.potrs(A, factor))

In [9]:
S = torch.inverse(S_inv)

In [10]:
mean_w = torch.mm(S, torch.mm(AT, torch.potrs(y, factor)))

In [11]:
mean_w

tensor([[ 0.5000],
        [-0.2500]])

In [12]:
torch.cuda.FloatTensor

torch.cuda.FloatTensor

In [23]:
torch.potrs(y_draw.reshape(50, 1), factor)

tensor([[ -1.9573],
        [ -2.7257],
        [ -0.2089],
        [ -4.9481],
        [  6.6254],
        [ -0.2063],
        [ -1.3462],
        [ -2.1594],
        [ -2.6813],
        [ -2.4262],
        [  0.5936],
        [  0.9059],
        [ 16.5186],
        [ -9.2776],
        [  2.2088],
        [ -3.4867],
        [ -8.1545],
        [ -0.3117],
        [ -2.2557],
        [ -0.1122],
        [ -1.7781],
        [  9.7956],
        [  1.9983],
        [ -3.3782],
        [ -0.3763],
        [  9.5655],
        [ -7.7860],
        [ -3.7563],
        [ -4.6705],
        [  1.4635],
        [  1.0612],
        [  1.1276],
        [  5.2580],
        [ -5.5185],
        [  1.0272],
        [  3.4027],
        [ -0.7522],
        [  1.5756],
        [  5.1021],
        [ -3.2521],
        [ -0.7761],
        [  0.1729],
        [ -2.3283],
        [  1.3841],
        [  3.3806],
        [ -7.0258],
        [  5.7635],
        [ -1.6885],
        [  3.5176],
        [  0.6798]])

In [ ]:
torch.potrf()

In [13]:
torch.inverse()

TypeError: inverse() missing 1 required positional arguments: "input"

In [18]:
mm = mean_w[0]

In [31]:
torch.mm(mean_w, mean_w.t())

tensor([[ 0.2500, -0.1250],
        [-0.1250,  0.0625]])

In [25]:
print("{}".format(mm[0]))

0.4999999701976776


In [10]:
torch.distributions.mul

AttributeError: module 'torch.distributions' has no attribute 'multivariate_normal'

In [ ]:
torch.distributions.multivar